### ISSUE TITLE
target blank in link

### ISSUE THREAD

**Issue by prhost** [vstelmakh/url-highlight#14]
Hello,

How to add the target on the link?

**Comment by vstelmakh** [comment]
To achieve this - create instance of [HtmlHighlighter](https://github.com/vstelmakh/url-highlight#highlighter) and provide `target` in second argument. See this code sample for an example:
```php
<?php
require __DIR__ . '/vendor/autoload.php';

use VStelmakh\UrlHighlight\Highlighter\HtmlHighlighter;
use VStelmakh\UrlHighlight\UrlHighlight;

$highlighter = new HtmlHighlighter('http', ['target' => '_blank']);
$urlHighlight = new UrlHighlight(null, $highlighter);

$urlHighlight->highlightUrls('Hello, http://example.com.');
// return: Hello, <a href="http://example.com" target="_blank">http://example.com</a>.
```

⚠️ This is a new feature released today.  You need to update to [v2.1](https://github.com/vstelmakh/url-highlight/releases/tag/v2.1.0)

**Comment by prhost** [comment]
thanks man

**Comment by vstelmakh** [comment]
Happy to help 😉
