### ISSUE TITLE
Installing with composer didn't work for PHP version 7.0.33.0

### ISSUE THREAD

**Issue by AverageGuy** [vstelmakh/url-highlight#17]
`composer require vstelmakh/url-highlight
                                                                                                    
  [InvalidArgumentException]                                                                        
  Could not find package vstelmakh/url-highlight at any version matching your PHP version 7.0.33.0  
                                                                                                    

require [--dev] [--prefer-source] [--prefer-dist] [--no-plugins] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

`

**Comment by vstelmakh** [comment]
Minimum supported version of PHP is 7.1, which is also end of life state already.
Would suggest you to update to one of the active support versions, see: https://www.php.net/supported-versions.php

**Comment by AverageGuy** [comment]
Great.  That's the default on Ubuntu 18.04.

Thanks,

Jim.
