### ISSUE TITLE
Feature request: Domain whitelist / blacklist

### ISSUE THREAD

**Issue by git-webmaster** [vstelmakh/url-highlight#28]
Hey. 
Nice little library, thanks a lot!

That would be really great to have a possibility to validate a domains (check if we are allowed to highlight a given link according to its domain like example.com).

In my case, i need to highlight only one domain - and of course i will achieve that in some hacky way, but i think that will be useful to implement it out of the box.

Cheers)

**Comment by vstelmakh** [comment]
Thanks for the feedback.
I'm not sure if I want to include host black/white lists. But will think about this more.

You could easily add any custom logic and achieve behaviour you want by creating a custom highlighter.
Here is an example:
```php
<?php

use VStelmakh\UrlHighlight\Highlighter\HtmlHighlighter;
use VStelmakh\UrlHighlight\Matcher\UrlMatch;

class CustomHighlighter extends HtmlHighlighter
{
    protected function getMatchHighlight(UrlMatch $match): string
    {
        return ($match->getHost() === 'your-website.com')
            ? parent::getMatchHighlight($match)
            : $match->getFullMatch();
    }
}
```
Usage:
```php
<?php
require __DIR__ . '/vendor/autoload.php';

use VStelmakh\UrlHighlight\Highlighter\CustomHighlighter;
use VStelmakh\UrlHighlight\UrlHighlight;

$urlHighlight = new UrlHighlight(null, new CustomHighlighter());
echo $urlHighlight->highlightUrls('Here is example.com and your-website.com.');
// Output: Here is example.com and <a href="http://your-website.com">your-website.com</a>.
```

For more details and examples see [Custom highlighter](https://github.com/vstelmakh/url-highlight/blob/master/docs/highlighter-custom.md)
