### ISSUE TITLE
very useful!!

### ISSUE THREAD

**Issue by vesper8** [vstelmakh/url-highlight#3]
well done!! it would be fantastic if you made one to highlight phone numbers.. another troublesome detection regex especially with all the edge cases with international numbers and what not.

it would also be nice if you made one for emails, although there are already some nice solutions out there for that

thanks for taking the time to make this!

**Comment by vstelmakh** [comment]
Thank you for the nice feedback. Good ideas, will think about it.

**Comment by karlerss** [comment]
Hey! Came here to say thanks as well! This is great.

To make sure this worked for my use case, I checked out the code and added this case to tests/UrlHiglightTest.php, just to make sure it didn't mess up my existing input. If this info was in readme or the main test file, it might be useful to others.

```
[
    null,
    'With html <img src="http://example.com/img.jpg"><a href="http://example.com/">Test</a>',
    'With html <img src="http://example.com/img.jpg"><a href="http://example.com/">Test</a>',
],
```

**Comment by vstelmakh** [comment]
> Hey! Came here to say thanks as well! This is great.
> 
> To make sure this worked for my use case, I checked out the code and added this case to tests/UrlHiglightTest.php, just to make sure it didn't mess up my existing input. If this info was in readme or the main test file, it might be useful to others.
> 
> ```
> [
>     null,
>     'With html <img src="http://example.com/img.jpg"><a href="http://example.com/">Test</a>',
>     'With html <img src="http://example.com/img.jpg"><a href="http://example.com/">Test</a>',
> ],
> ```

Thanks for the feedback. Good point, will do this soon 🙂
