### ISSUE TITLE
Emails are incorrectly recognized as URL.

### ISSUE THREAD

**Issue by InfraBackend** [vstelmakh/url-highlight#36]
$urlHighlight->getUrls('sc@icloud.com');

Will the email be used as a url, if avoided?

**Comment by vstelmakh** [comment]
Hello @DylanBack 👋 Thank you for your interest in Url highlight library.

I'm not sure if I get your issue correctly. There is a way to disable email matching. It cold be done by providing [Validator](https://github.com/vstelmakh/url-highlight/blob/master/src/Validator/Validator.php) instance with 4th argument (matchEmails) as `false`. See corresponding [validator documentation section](https://github.com/vstelmakh/url-highlight#validator) for details.

Here is a small example with disabled email matching:
```php
<?php

require __DIR__ . '/vendor/autoload.php';

use VStelmakh\UrlHighlight\UrlHighlight;
use VStelmakh\UrlHighlight\Validator\Validator;

$validator = new Validator(true, [], [], false);
$urlHighlight = new UrlHighlight($validator);
$result = $urlHighlight->getUrls('Match example.com but not nsc@icloud.com');

var_dump($result);

// Output:
//
// array(1) {
//  [0]=>
//  string(11) "example.com"
// }
```
